### ISSUE TITLE
设置通知

### ISSUE THREAD

**Issue by wuxiaoyu223** [Reborn14/To-Do-Master#1]
非常感谢您的实施策略，作为一个纯粹的小白用户，从注册notion、github开始，按照您的实施策略，我成功完成了配置，并且可以使用了。我在使用的过程中有一个问题，例如我想设置下午4点的会议，并提前15分钟通过APP PUSH发通知给我，我发现无法设置通知(remind)，不知道是我的使用有问题还是未配置，无法配置，希望能跟您交流。非常感谢！

**Comment by Reborn14** [comment]
看了一下文档，notion api 对于日期字段暂时不支持设置 remind。所以没法实现呢
